language: android
jdk: oraclejdk8

# 开启基于容器的Travis CI任务，让编译效率更高
sudo: false


android:
  components:
    # 构建项目所用的BuildTools版本
    - build-tools-29.0.1
    # 用来编译项目的SDK版本
    - android-29
before_script:
  - chmod +x gradlew
  
  
script:
  # 生成release apk包
  - ./gradlew assembleRelease
deploy:
  # 部署到GitHub Release。
  # 除此之外，Travis CI还支持发布到fir.im、AWS、Google App Engine等
  provider: releases
  # Github oauth token
  api_key: ${GH_TOKEN}
  # 部署文件路径；对于Android就部署生成的 apk 文件
  file: "/test.apk"
  # 避免 Travis CI在部署之前清空生成的APK文件
  skip_cleanup: true
